# Generated by Django 5.1.4 on 2024-12-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='nombre_mascota',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
